[chain_a]
type = "cosmos"
name = "chain-a"
chain_id = "ibc-0"
rpc_url = "http://127.0.0.1:27030"
grpc_url = "http://127.0.0.1:27032"
websocket_url = "ws://127.0.0.1:27030/websocket"
client_id = "7-tendermint-0"
connection_id = "connection-0"
account_prefix = "cosmos"
store_prefix = 'ibc'
key_name = "alice"

[chain_b]
type = "cosmos"
name = "chain-b"
chain_id = "ibc-1"
rpc_url = "http://127.0.0.1:27040"
grpc_url = "http://127.0.0.1:27042"
websocket_url = "ws://127.0.0.1:27040/websocket"
client_id = "7-tendermint-0"
connection_id = "connection-0"
account_prefix = "cosmos"
store_prefix = 'ibc'
key_name = "bob"

[core]
prometheus_endpoint = "https://127.0.0.1"